package logic;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;

public class CountryList {

    public static String getCountry(int index){return country.get(index);}

    public static void loading(int size){
        country = new ArrayList<String>(size);
        ArrayList<Integer> indexList = new ArrayList<Integer>();
        Random rnd = new Random();
        int index;
        for (int i = 0; i < size; i+=2) {
            index = rnd.nextInt(countryList.length - 1);
            while (indexList.contains(index)){
                index = rnd.nextInt(countryList.length - 1);
            }
            indexList.add(index);
//                if(index == countryList.length)
//                    index = 0;
            country.add(i, countryList[index]);
            country.add(i+1, countryList[index]);
        }
    }

    public static void shuffle(){
        Collections.shuffle(country);
    }

    public static ArrayList<String> getCountryList(){ return country; }

    private static ArrayList<String> country;

    private static String[] countryList =
            {
                "Afghanistan",
                "Aland_islands",
                "Albania",
                "Algeria",
                "American_samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antarctica",
                "Antigua_and_barbuda",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bermuda",
                "Bhutan",
                "Biot",
                "Bolivia",
                "Bonaire",
                "Bosnian",
                "Botswana",
                "Bouvet_island",
                "Brazil",
                "British_antarctic_territory",
                "British_virgin_islands",
                "Brunei",
                "Bulgaria",
                "Burkina_faso",
                "Burma",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Canada",
                "Cape_verde",
                "Cascadia",
                "Cayman_islands",
                "Central_african_republic",
                "Chad",
                "Chile",
                "China",
                "Christmas_island",
                "Cocos_islands",
                "Colombia",
                "Comoros",
                "Congo",
                "Congo_kinshasa",
                "Cook_islands",
                "Costa_rica",
                "Croatian",
                "Cuba",
                "Curacao",
                "Cyprus",
                "Czech_republic",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican_republic",
                "East_timor",
                "Ecuador",
                "Egypt",
                "El_salvador",
                "England",
                "Equatorial_guinea",
                "Eritrea",
                "Estonia",
                "Ethiopia",
                "European_union",
                "Ex_yugoslavia",
                "Falkland_islands",
                "Faroe_islands",
                "Fiji",
                "Finland",
                "France",
                "French_polynesia",
                "French_southern_territories",
                "Gabon",
                "Gambia",
                "Georgia",
                "Germany",
                "Ghana",
                "Gibraltar",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guinea",
                "Guinea_bissau",
                "Guyana",
                "Haiti",
                "Holy_see",
                "Honduras",
                "Hong_kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Ireland",
                "Isle_of_man",
                "Israel",
                "Italy",
                "Ivory_coast",
                "Jamaica",
                "Jan_mayen",
                "Japan",
                "Jarvis_island",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Kosovo",
                "Kuwait",
                "Kyrgyzstan",
                "Laos",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macau",
                "Macedonia",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall_islands",
                "Martinique",
                "Mauritania",
                "Mauritius",
                "Mayotte",
                "Mexico",
                "Micronesia",
                "Moldova",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands",
                "Netherlands_antilles",
                "New_caledonia",
                "New_zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk_island",
                "Northern_ireland",
                "Northern_mariana_islands",
                "North_korea",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestinian_territory",
                "Panama",
                "Papua_new_guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Pitcairn",
                "Poland",
                "Portugal",
                "Puerto_rico",
                "Qatar",
                "Reunion",
                "Romania",
                "Russia",
                "Rwanda",
                "Saint_barthelemy",
                "Saint_helena",
                "Saint_helena_and_dependencies",
                "Saint_kitts_and_nevis",
                "Saint_lucia",
                "Saint_martin",
                "Saint_pierre_and_miquelon",
                "Samoa",
                "San_marino",
                "Sao_tome_and_principe",
                "Saudi_arabia",
                "Scotland",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra_leone",
                "Singapore",
                "Sint_eustatius",
                "Sint_maarten",
                "Slovakia",
                "Slovenia",
                "Smom",
                "Solomon_islands",
                "Somalia",
                "South_africa",
                "South_georgia",
                "South_Korea",
                "South_sudan",
                "Spain",
                "Spm",
                "Sri_lanka",
                "Sudan",
                "Suriname",
                "Svalbard",
                "Svg",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syria",
                "Taiwan",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Timor_leste",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad_and_tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Turks_and_caicos_islands",
                "Tuvalu",
                "Uganda",
                "Ukraine",
                "United_arab_emirates",
                "United_kingdom",
                "United_states",
                "Unknown",
                "Uruguay",
                "Ussr",
                "Uzbekistan",
                "Vanuatu",
                "Vatican_city",
                "Venezuela",
                "Vietnam",
                "Virgin_islands",
                "Wales",
                "Wallis_and_futuna",
                "Western_sahara",
                "Yemen",
                "Yugoslavia",
                "Zambia",
                "Zimbabwe"
            };
}
