package logic;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;

public class CountryList {

    public static String getCountry(int index){return country.get(index);}

    public static void loading(int size){
        country = new ArrayList<String>(size);
        ArrayList<Integer> indexList = new ArrayList<Integer>();
        Random rnd = new Random();
        int index;
        for (int i = 0; i < size; i+=2) {
            index = rnd.nextInt(countryList.length - 1);
            while (indexList.contains(index)){
                index = rnd.nextInt(countryList.length - 1);
            }
            indexList.add(index);
//                if(index == countryList.length)
//                    index = 0;
            country.add(i, countryList[index]);
            country.add(i+1, countryList[index]);
        }
    }

    public static void shuffle(){
        Collections.shuffle(country);
    }

    public static ArrayList<String> getCountryList(){ return country; }

    private static ArrayList<String> country;

    private static String[] countryList = {
//            "Abkhazia",
            "Afghanistan",
//            "Aland",
            "Albania",
            "Algeria",
            "American_Samoa",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antarctica",
            "Antigua_and_Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
//            "Basque Country",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
//            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "British_Antarctic_Territory",
            "British_Virgin_Islands",
            "Brunei",
            "Bulgaria",
            "Burkina_Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
//            "Canary Islands",
            "Cape_Verde",
            "Cayman_Islands",
            "Central_African_Republic",
            "Chad",
            "Chile",
            "China",
            "Christmas_Island",
//            "Cocos Keeling Islands",
            "Colombia",
//            "Commonwealth",
            "Comoros",
            "Cook_Islands",
            "Costa_Rica",
//            "Cote dIvoire",
//            "Croatia",
            "Cuba",
            "Curacao",
            "Cyprus",
            "Czech_Republic",
//            "Democratic Republic of the Congo",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican_Republic",
            "East_Timor",
            "Ecuador",
            "Egypt",
            "El_Salvador",
            "England",
            "Equatorial_Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
//            "European Union",
            "Falkland_Islands",
//            "Faroes",
            "Fiji",
            "Finland",
            "France",
            "French_Polynesia",
            "French_Southern_Territories",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
//            "GoSquared",
            "Greece",
            "Greenland",
            "Grenada",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea_Bissau",
            "Guinea",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hong_Kong",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle_of_Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
//            "Mars",
            "Marshall_Islands",
            "Martinique",
            "Mauritania",
            "Mauritius",
            "Mayotte",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
//            "Nagorno Karabakh",
            "Namibia",
//            "NATO",
            "Nauru",
            "Nepal",
            "Netherlands_Antilles",
            "Netherlands",
            "New_Caledonia",
            "New_Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norfolk_Island",
            "North_Korea",
//            "Northern Cyprus",
            "Northern_Mariana_Islands",
            "Norway",
            "Olympics",
            "Oman",
            "Pakistan",
            "Palau",
//            "Palestine",
            "Panama",
            "Papua_New_Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
//            "Pitcairn Islands",
            "Poland",
            "Portugal",
            "Puerto_Rico",
            "Qatar",
//            "Red Cross",
//            "Republic of the Congo",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint_Barthelemy",
            "Saint_Helena",
            "Saint_Kitts and Nevis",
            "Saint_Lucia",
            "Saint_Martin",
            "Saint_Vincent_and_the_Grenadines",
            "Samoa",
            "San_Marino",
            "Sao_Tome_and_Principe",
            "Saudi_Arabia",
            "Scotland",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra_Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon_Islands",
            "Somalia",
//            "Somaliland",
            "South_Africa",
//            "South Georgia and the South Sandwich Islands",
//            "South Korea",
//            "South Ossetia",
            "South_Sudan",
            "Spain",
            "Sri_Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tokelau",
            "Tonga",
            "Trinidad_and_Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Turks_and_Caicos_Islands",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United_Arab_Emirates",
            "United_Kingdom",
//            "United Nations",
            "United_States",
            "Unknown",
            "Uruguay",
//            "US Virgin Islands",
            "Uzbekistan",
            "Vanuatu",
            "Vatican_City",
            "Venezuela",
            "Vietnam",
            "Wales",
            "Wallis_And_Futuna",
            "Western_Sahara",
            "Yemen",
            "Zambia",
            "Zimbabwe"};
}
